spring.application.name=aquahaven

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/aquahaven
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=aquahaven_super_secret_key_must_be_at_least_256_bits_long_for_hs256
jwt.expiration=86400000